query (
  $login: String!
  $nameWithOwner: Boolean!
  $onlyAnswers: Boolean!
  $cursor: String
) {
  user(login: $login) {
    repositoryDiscussionComments(
      first: 100
      after: $cursor
      onlyAnswers: $onlyAnswers
    ) {
      nodes {
        discussion {
          repository {
            name
            nameWithOwner @include(if: $nameWithOwner)
            owner {
              avatarUrl
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
