query ($login: String!, $onlyAnswers: Boolean!, $cursor: String) {
  user(login: $login) {
    repo: repositoryDiscussionComments(
      first: 100
      after: $cursor
      onlyAnswers: $onlyAnswers
    ) {
      nodes {
        discussion {
          repository {
            nameWithOwner
            owner {
              avatarUrl
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
