query (
  $login: String!
  $nameWithOwner: Boolean!
  $cursor: String
  $contributionTypes: [RepositoryContributionType]
) {
  user(login: $login) {
    repositoriesContributedTo(
      first: 100
      after: $cursor
      contributionTypes: $contributionTypes
    ) {
      totalCount
      nodes {
        stargazerCount
        isInOrganization
        name
        nameWithOwner @include(if: $nameWithOwner)
        owner {
          avatarUrl
          login
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
